image: registry.gitlab.com/technocreatives/internal/android-ci:29

variables:
  GIT_STRATEGY: clone

stages:
  - test
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
     - .gradle

test:
  stage: test
  script:
     - ./gradlew check
  only:
    refs:
      - master
      - merge_requests

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    refs:
      - master
