name: Beckon workflows

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  beckon-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Beckon Test
        run: ./gradlew :beckon:test

  beckon-mesh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Beckon Mesh Test
        run: ./gradlew :beckon-mesh:test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew assemble
